codecov:
  require_ci_to_pass: false
  notify:
    after_n_builds: 1

coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 85%
        informational: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
